name: Docker Compose Metadata

on:
  workflow_call:
    inputs:
      docker-compose-file:
        type: string
        description: |
          The path to the docker compose file, relative to the git root. Defaults to "docker/docker-compose.yml"
        required: false
        default: "docker/docker-compose.yml"
      skip:
        type: boolean
        description: Whether to skip the workflow or not.
        required: false
        default: false
    outputs:
      metadata:
        description: A stringified JSON object of the docker compose file.
        value: ${{ jobs.docker-compose-metadata.outputs.metadata }}

permissions:
  contents: read

jobs:
<<<<<<< HEAD
  docker-compose-metadata:
    if: ${{ !inputs.skip }}
=======
  example-job:
>>>>>>> template/master
    runs-on: ubuntu-22.04
    permissions:
      contents: read
    outputs:
      metadata: ${{ steps.metadata.outputs.metadata }}
    steps:
<<<<<<< HEAD
      - uses: actions/checkout@v4
      - name: Parse docker-compose metadata
        id: metadata
=======
      # This condition should be on every step.
      - if: ${{ !inputs.skip }}
        id: example-step
        name: Example step
        env:
          BIG_SECRET: ${{ secrets.example-secret }}
>>>>>>> template/master
        run: |
          metadata="$(yq -o json -e '.' ${{ inputs.docker-compose-file }} | jq -c)"
          echo "metadata=${metadata}" >> "${GITHUB_OUTPUT}"
